on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

 
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps: 

    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Compilacion JAVA
      run: |
          chmod +x gradlew
          ./gradlew build

    - name: Copia de Jar a Raiz de proyecto
      run: 
           cp $GITHUB_WORKSPACE/build/libs/spring-petclinic-2.6.0.jar .
           chmod 777 spring-petclinic-2.6.0.jar
           ls -ltra

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      with:
        project: 'final_lab_sast2' 
        path: '.'
        format: 'html'
        
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
        
